class CeremonialCounty < ApplicationRecord
  has_many :lieutenants, dependent: :nullify
  has_many :form_answers, dependent: :nullify

  validates :name, presence: true

  scope :ordered, -> { order(:country, :name) }

  COUNTY_MAPPINGS = {
    "England": [
      "Bedfordshire",
      "Berkshire",
      "Buckinghamshire",
      "Cambridgeshire",
      "Cornwall",
      "County Durham",
      "Cumbria",
      "Derbyshire",
      "Devon",
      "Dorset",
      "East Sussex",
      "Essex",
      "Gloucestershire",
      "Greater London",
      "Greater Manchester",
      "Hampshire",
      "Herefordshire",
      "Isle of Man",
      "Kent",
      "Lancashire",
      "Leicestershire",
      "Lincolnshire",
      "Merseyside",
      "Norfolk",
      "North Yorkshire",
      "Northamptonshire",
      "Northumberland",
      "Nottinghamshire",
      "Oxfordshire",
      "Rutland",
      "Shropshire",
      "Somerset",
      "South Yorkshire",
      "Staffordshire",
      "Suffolk",
      "Surrey",
      "The City and County of Bristol",
      "The East Riding of Yorkshire",
      "Isle of Wight",
      "The West Midlands",
      "Tyne and Wear",
      "Warwickshire",
      "West Sussex",
      "West Yorkshire",
      "Wiltshire",
      "Worcestershire"
    ],
    "Islands": [
      "Guernsey",
      "Jersey"
    ],
    "Northern Ireland": [
      "County Antrim",
      "County Armagh",
      "County Borough of Belfast",
      "County Borough of Londonderry",
      "County Down",
      "County Fermanagh",
      "County Tyrone",
      "The City of Londonderry"
    ],
    "Scotland": [
      "Aberdeenshire",
      "Angus",
      "Argyll and Bute",
      "Ayrshire and Arran",
      "Banffshire",
      "Berwickshire",
      "Caithness",
      "Clackmannanshire",
      "Dumfries and Galloway",
      "Dunbartonshire",
      "East Lothian",
      "Fife",
      "Inverness",
      "Kincardineshire",
      "Lanarkshire",
      "Midlothian",
      "Moray",
      "Nairn",
      "Orkney",
      "Perth and Kinross",
      "Renfrewshire",
      "Ross and Cromarty",
      "Roxburgh Etterick and Lauderdale",
      "Shetland",
      "Stirling and Falkirk",
      "Sutherland",
      "The City of Aberdeen",
      "The City of Dundee",
      "The City of Edinburgh",
      "The City of Glasgow",
      "The Stewartry of Kirkcudbright",
      "The Western Isles",
      "Tweeddale",
      "West Lothian",
      "Wigtown"
    ],
    "Wales": [
      "Clwyd",
      "Dyfed",
      "Gwent",
      "Gwynedd",
      "Mid Glamorgan",
      "Powys",
      "South Glamorgan",
      "West Glamorgan"
    ]
  }
end
