name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_DB: qavs_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 15s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    env:
      DISPLAY_SOCIAL_MOBILITY_AWARD: true
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/qavs_test'
      DOCKER_TLS_CERTDIR: ''
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libcurl4 libcurl3-gnutls libcurl4-openssl-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.231.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: yarn
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile
      - name: Setup database
        run: bundle exec rails db:prepare
      - name: Run tests
        run: |
          RAILS_DISABLE_TEST_LOG=true bundle exec rspec --format RSpec::Github::Formatter --format progress
